-- =========================================================================
-- Snaxify Database Security: Enable Row Level Security (RLS) & Encryption
-- Run this script in your Supabase SQL Editor (https://supabase.com/dashboard)
-- =========================================================================

-- 1. Enable pgcrypto extension for data encryption & decryption
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. ENABLE ROW LEVEL SECURITY (RLS) ON ORDERS TABLE
ALTER TABLE IF EXISTS orders ENABLE ROW LEVEL SECURITY;

-- Allow public / anon users to INSERT orders (needed during checkout)
DROP POLICY IF EXISTS "Allow anonymous insert orders" ON orders;
CREATE POLICY "Allow anonymous insert orders" 
  ON orders 
  FOR INSERT 
  TO anon, authenticated 
  WITH CHECK (true);

-- Deny public / anon users from SELECTING orders
-- Only backend service_role key can read all customer orders
DROP POLICY IF EXISTS "Allow service_role full access on orders" ON orders;
CREATE POLICY "Allow service_role full access on orders" 
  ON orders 
  FOR ALL 
  TO service_role 
  USING (true) 
  WITH CHECK (true);

-- 3. ENABLE ROW LEVEL SECURITY (RLS) ON COUPONS TABLE
ALTER TABLE IF EXISTS coupons ENABLE ROW LEVEL SECURITY;

-- Allow anonymous users to READ ONLY active coupons
DROP POLICY IF EXISTS "Allow public read active coupons" ON coupons;
CREATE POLICY "Allow public read active coupons" 
  ON coupons 
  FOR SELECT 
  TO anon, authenticated 
  USING (enabled = true);

-- Allow service_role key full CRUD on coupons
DROP POLICY IF EXISTS "Allow service_role full access on coupons" ON coupons;
CREATE POLICY "Allow service_role full access on coupons" 
  ON coupons 
  FOR ALL 
  TO service_role 
  USING (true) 
  WITH CHECK (true);

-- 4. ENABLE ROW LEVEL SECURITY (RLS) ON SHOP_SETTINGS TABLE
CREATE TABLE IF NOT EXISTS shop_settings (
  id int PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  manual_override text DEFAULT NULL
);

INSERT INTO shop_settings (id, manual_override) VALUES (1, NULL)
  ON CONFLICT (id) DO NOTHING;

ALTER TABLE shop_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read shop_settings" ON shop_settings;
CREATE POLICY "Allow public read shop_settings"
  ON shop_settings FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "Allow service_role write shop_settings" ON shop_settings;
CREATE POLICY "Allow service_role write shop_settings"
  ON shop_settings FOR ALL TO service_role
  USING (true) WITH CHECK (true);

-- 5. ENABLE ROW LEVEL SECURITY (RLS) ON ITEM_REQUESTS TABLE
CREATE TABLE IF NOT EXISTS item_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text DEFAULT 'Anonymous',
  item text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE item_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anonymous insert item_requests" ON item_requests;
CREATE POLICY "Allow anonymous insert item_requests"
  ON item_requests FOR INSERT TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Allow service_role full access item_requests" ON item_requests;
CREATE POLICY "Allow service_role full access item_requests"
  ON item_requests FOR ALL TO service_role
  USING (true) WITH CHECK (true);

-- 6. ENCRYPT SENSITIVE DATA (Column Level Encryption Example)
-- If encrypting sensitive customer data (such as contact, notes, or payment ref):
-- UPDATE orders SET customer_name = pgp_sym_encrypt(customer_name, 'your-secure-encryption-key');
-- SELECT pgp_sym_decrypt(customer_name::bytea, 'your-secure-encryption-key') AS decrypted_name FROM orders;
